# Generated by Django 3.0.9 on 2020-08-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200830_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='imageURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
