# Generated by Django 3.0.9 on 2020-09-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200831_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
