# Generated by Django 3.0.9 on 2020-09-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200906_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.PositiveIntegerField(),
        ),
    ]
